### PR TITLE
Pass context and query info to sorter callback functions

### PR DESCRIPTION
**Pull request by geoffp**
This change addresses a need I had to write a sorter function that prioritizes result datums that have certain attributes that are closer to the query string than others. All I needed was access to more information from inside the sorter function, so this change is pretty non-invasive, and should give developers lots of added flexibility to sort results based on the query.

I've passed around some "this" context and added a closure so that "this" in the sorter will refer to the Bloodhound instance, and more importantly, allow sorter function authors to accept a third parameter, which provides the string and tokenized forms of the query. The signature of the function passed to Array.prototype.sort() is preserved exactly as (a, b).

The queryInfo object is created in the get() method so the query tokenizer can be run once per query and not every time the callback executes.

This should solve https://github.com/twitter/typeahead.js/issues/817.

### CODE REVIEW

**Comment by raysuelzer** [comment]
Highly useful.

**Comment by raysuelzer** [comment]
This should definitely be pulled in. I can now actually access the current query on sorting and did something similar for filters... I don't see how people have been using this without the ability to implement their own sorting algos that take into account the search. **shrug**

**Comment by geoffp** [comment]
For what it's worth, this patch has been in production at a State of Minnesota web app for over a year with good results.

**Comment by jharding** [comment]
Just wanted to let you know that this functionality will be landing in v0.11.2 (see #1191). I pretty much took what you did and updated it to work with current master. Thanks for the PR and sorry it took so long.

**Pull request closed without merging**
