### PR TITLE
Bugfix - show currect number of async suggestions when less than limit [Fix #1218]

### LINKED ISSUE #1218: Remote completion
I have a very strange behavior with remote data.
I've made a self explaining JSFiddle [that you can find here](http://jsfiddle.net/md88bgyc/3/).

It works well with 1 result, or two, or more than 5. Otherwise it's completly messed up.

### PR DESCRIPTION
**Pull request by joekur**
See #1218

### CODE REVIEW

**Comment by kylecrum** [comment]
Same as #1212 and https://github.com/twitter/typeahead.js/pull/1233 . There are several solutions to choose from :smile:

**Comment by vvo** [comment]
hello @jharding, current typeahead completely fails because of this. It's already released on npm, jsdelivr etc.. but still fails.

Thanks for the work thought.

**Comment by wkornewald** [comment]
Please take a look at #1277. Not only the results count is wrong, but also the results themselves.

**Comment by vvo** [comment]
Wonderful

**Comment by joekur** [comment]
@wkornewald - to clarify, are you saying my suggested change gives the wrong results? Could you elaborate? Maybe there is an additional test that's needed?

At this point I think @jharding just needs to choose the best implementation and close the rest of these pulls.

**Comment by wkornewald** [comment]
@joekur Actually, yours is correct and simpler than mine. Was in a hurry and my solution uses Math.min() to be on the safe side, but that's not really necessary.

**Comment by cstoneham** [comment]
Is this going in? I ran into this issue recently.

**Comment by joekur** [comment]
@cstoneham see https://github.com/twitter/typeahead.js/issues/1424

**Comment by cstoneham** [comment]
@joekur Ah, thanks for the heads up.

**Pull request closed without merging**
