### PR TITLE
Fixes #1415 - Suggestions not displaying

### LINKED ISSUE #1415: Suggestions not displaying
I have replicated the issue here
http://codepen.io/benguela/pen/epMMyo

In the field enter the letters

sco 

bloodhound fetches suggestions but they are not displayed. if however you enter

scot

bloodhound fetches suggestions and they are displayed.
I have a workaround at the moment where in line 1724 of the typeahead bundle I changed

that._append(query, suggestions.slice(0, that.limit - rendered));

to

that._append(query, suggestions.slice(0, that.limit));

but this is not the correct solution.

### PR DESCRIPTION
**Pull request by nimzco**
See: https://github.com/twitter/typeahead.js/issues/1415

### CODE REVIEW

**Comment by nept** [comment]
:+1:

**Comment by fritsjanb** [comment]
+1

**Comment by rafaellyra** [comment]
:+1:

**Comment by technid** [comment]
+1

**Comment by valentinkostadinov** [comment]
+1

**Comment by synth** [comment]
+1 Using corejavascripts fork until this is merged: https://github.com/corejavascript/typeahead.js

**Comment by laudeco** [comment]
+1

**Comment by tonivdv** [comment]
+1

**Comment by he8us** [comment]
+1

**Comment by JodyLognoul** [comment]
+1

**Comment by delsoft** [comment]
+1

**Comment by beowulfenator** [comment]
+1

**Comment by tabaliov** [comment]
+1

**Comment by zdraganov** [comment]
+1

**Comment by adamof** [comment]
+1

**Pull request closed without merging**
