### PR TITLE
autoSelect Option

### PR DESCRIPTION
**Pull request by hongz1**
‘autoSelect’ option allows to select suggestion in the input box with
hitting enter or tab key. This option is available to both single and
multiple datasets.

### CODE REVIEW

**Comment by aerickson** [comment]
Please accept this. It's working well for me.

**Comment by DanielApt** [comment]
@jharding Could you please accept this pull-request? 

It's working as expected, and this is definitely a feature that needs to be added again.

**Comment by cafesanu** [comment]
@jharding any chance to get this merged soon? It's working perfectly for me locally as well.

**Comment by namtab00** [comment]
@cafesanu @aerickson @DanielApt @hongz1 
This repo seems abandoned.. some kind souls continue maintaing it here: https://github.com/corejavascript/typeahead.js
I'd say the useful thing to do is sending pull requests and issues there.

**Comment by aerickson** [comment]
@namtab00 Thanks. It looks like @DanielApt has filed https://github.com/corejavascript/typeahead.js/pull/54.

**Comment by fedesoria** [comment]
```
$('.typeahead').bind('typeahead:render', function() {
  $('.typeahead').typeahead('moveCursor', +1);
});
```

**Comment by hongz1** [comment]
No need to request pull in here since @DanielApt filled [corejavescript#54](https://github.com/corejavascript/typeahead.js/pull/54)

**Pull request closed without merging**
