### PR TITLE
Avoid reference error when query is undefined

### PR DESCRIPTION
**Pull request by anderssonjohan**
I'm unsure if my code is using this project's coding style for checking for undefined, please comment if this is completely wrong.

### CODE REVIEW

**Comment by jharding** [comment]
What's the scenario where `this.query` is `undefined`?

**Comment by anderssonjohan** [comment]
@jharding Thank you for the feedback. I used this with a custom binding with Knockout.js where I call the val-method with the bound value. I believe a failing test would be something simple as:

```
$(element).typeahead('val', undefined);
```

It seems v0.11 contains a decent amount of rewrites so I will test the new release and submit a new pull request if this issue persists.

**Comment by jharding** [comment]
Going to reopen to track fixing this behavior. Should be an easy fix.

**Comment by anderssonjohan** [comment]
@jharding Ok - please let me know if you need more info. I'm happy if I can help.

**Comment by jharding** [comment]
Added a PR that should prevent this, see #1199.

**Pull request closed without merging**
