### PR TITLE
Fix bad async suggestions rendering logic

### PR DESCRIPTION
**Pull request by jharding**

### CODE REVIEW

**Comment by mayank-saavn** [comment]
This fixes it. Thanks.

**Comment by jarthod** [comment]
#1212 also fixes but with tests ;)

**Comment by PacciniBruno** [comment]
Same here :'(

**Comment by ultimatemanu** [comment]
Same for us :) Spent also a few hours to find where the problem was.

**Comment by j-kwon** [comment]
same here, look forward to merging into the master asap.

**Comment by gremo** [comment]
#1200 works for you guys? Because for me it doesn't. Limit: 5, result set: 5, shown: 0. #1212 fixes the problem at least for me.

**Comment by eins78** [comment]
I can confirm that pr #1200 (this) does not fix issue #1232, but pr #1212 does (and, as others have pointed out comes with a test).

**Comment by Floby** [comment]
Any idea when this is going into master ?

**Comment by davis** [comment]
ah i finally found why this is happening :D

**Comment by terrasoff** [comment]
not working... forced to switch to fork #1212

**Comment by isdampe** [comment]
+1 for merge...

**Comment by danielgasser** [comment]
Still not in master? How do I fix that and rebundle all files?

**Pull request merged**
