### PR TITLE
Grouping by category from datum object

### PR DESCRIPTION
**Pull request by migg24**
Added categories to the dropdown that are coming from the datum objects. For every new category in the next datum object it adds an unselectable `tt-sugestion-category` element before the suggestion containing the new category.

Related to comment https://github.com/twitter/typeahead.js/issues/11#issuecomment-13857058

Usage:

```
$('#the-basics .typeahead').typeahead({
  hint: true,
  highlight: true,
  minLength: 1
},
{
  name: 'cities',
  displayKey: 'name',
  displayCategory: 'state',
  source: substringMatcher(cities)
});
```

Assuming a city datum object looking like this:

```
{
  name: "Montgomery",
  state: "Alabama"
}
```

Also added a `templates.category.header` to use a custom category header template.

### CODE REVIEW

**Comment by maximelamure** [comment]
+1 to merge this PR. TypeHead should not be depend on Bloodhound for this "common" scenario.

**Comment by gigamorph** [comment]
migg24's patch works great for me. I needed it to categorize the suggestions from a remote search API according to the matched field. I hope this will get merged to the next release.

**Comment by sirianni** [comment]
Any interest in rebasing this patch against the latest?  Looks like there need to be some changes made to support the 'dataset' changes upstream.

**Comment by migg24** [comment]
You appreciate it so much that it gets ignored for 5 years? Lets just close this. Thank you bot 😂

**Comment by brendanfalkowski** [comment]
@migg24 — LOL, I remember this. I ended up writing a tiny library for typeahead instead, and made it open source recently. Learned a bunch and still using it in a few places: https://github.com/gravitydepartment/typeahead

**Pull request closed without merging**
