### PR TITLE
autoSelect Option

### PR DESCRIPTION
**Pull request by hongz1**
‘autoSelect’ option allows to select suggestion in the input box with
hitting enter or tab key. This option is available to both single and
multiple datasets.

### CODE REVIEW

**Comment by zachgarwood** [comment]
:+1:

**Comment by tbodev** [comment]
Great. Exactly what I need for for my current project. But defaulting the autocomplete option to "false" it would break compatibility with v0.11.1

**Comment by hongz1** [comment]
The latest request pull (6696c43) I posted is based on the v0.11.1 and I tested with default option ('false') and worked fine. I had to use this functionality for my project and it is working great to me.

**Comment by PacciniBruno** [comment]
Thanks a lot for that :) exactly what I needed. Working great for me to.

**Comment by hasghari** [comment]
You should not check in build artifacts when creating a pull request. Could you please remove the changes under the `dist` directory?

**Comment by hasghari** [comment]
@hongz1 You should also squash your 3 commits into 1. There should be no "Revert" commit in the history.

**Comment by hongz1** [comment]
I tried but couldn't figure it out so please tell me how to clean them up

**Comment by hasghari** [comment]
Read up on `git rebase -i`. https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i

**Comment by hongz1** [comment]
ok. will do it. thanks.

**Comment by hasghari** [comment]
@hongz1 I did not mean you should remove the files under the `dist` directory entirely. I meant that you should not be committing any changes to files under that directory. 

The `dist` files will be built by the project maintainer when releasing a new version.

**Comment by hongz1** [comment]
ok got it. I removed dist dir. I am currently using gut hub app in mac so how can I rebase them?

**Comment by hongz1** [comment]
@hasghari Did I do correctly?

**Comment by bronson** [comment]
Hm, no...  When the [Commits tab](https://github.com/twitter/typeahead.js/pull/1252/commits) doesn't contain any reverts or merges, you'll know your rebase worked correctly.

What you want to do:

```
git rebase -i origin/master
```

This tells git to rebase all commits from origin/master to the current HEAD.  In other words, all your commits.

Then squash all your commits into one, and give that commit a good message.  Then, when it looks good, force push.

More info: https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history

**Comment by hongz1** [comment]
Thank you for suggestions. I tried everything based on what you guys suggested, but didn't work for me.
I closed this commit and re-created a pull request #1356

**Pull request closed without merging**
