### PR TITLE
Add UMD wrapper

### PR DESCRIPTION
**Pull request by timsnadden**
This plugin currently relies on window.jQuery. This patch adds a UMD wrapper so that it can be used in environments where jQuery is not a global. e.g. requirejs module with noconflict.

### CODE REVIEW

**Comment by skitterm** [comment]
Is there now an AMD version of typeahead?

**Comment by timsnadden** [comment]
If you use my fork there is! Unfortunately it seems like this repo has been abandoned.

**Comment by olizilla** [comment]
+1 for this. @JakeHarding are you looking for maintainers?

**Comment by olizilla** [comment]
@timsnadden I'm trying out your PR. In it's current state, the Bloodhound factory function doesn't return an instance of Bloodhound but attaches it to the global regardless. I haven't fiddled with UMD enough, but that seems like it needs tweaking. Any thoughts? Is it working fine for you?

**Comment by timsnadden** [comment]
I'm not using bloodhound in my project so haven't come across this issue. There are references in the code to ```root.Bloodhound```. There is also a ```noConflict``` function which may be clues. All my PR does is wrap the existing code and not depend on window.jQuery.

**Comment by jharding** [comment]
This was done in v0.11. Thanks for the PR.

**Pull request closed without merging**
